var TypeErrorCustom;
(function (TypeErrorCustom) {
    TypeErrorCustom["MAPPING_NOT_FOUND"] = "mapping-not-found";
})(TypeErrorCustom || (TypeErrorCustom = {}));
var TypeErrorDefault;
(function (TypeErrorDefault) {
    TypeErrorDefault["CONTINUE"] = "CONTINUE";
    TypeErrorDefault["SWITCHING_PROTOCOLS"] = "SWITCHING_PROTOCOLS";
    TypeErrorDefault["PROCESSING"] = "PROCESSING";
    TypeErrorDefault["EARLY_HINTS"] = "EARLY_HINTS";
    TypeErrorDefault["OK"] = "OK";
    TypeErrorDefault["CREATED"] = "CREATED";
    TypeErrorDefault["ACCEPTED"] = "ACCEPTED";
    TypeErrorDefault["NON_AUTHORITATIVE_INFORMATION"] = "NON_AUTHORITATIVE_INFORMATION";
    TypeErrorDefault["NO_CONTENT"] = "NO_CONTENT";
    TypeErrorDefault["RESET_CONTENT"] = "RESET_CONTENT";
    TypeErrorDefault["PARTIAL_CONTENT"] = "PARTIAL_CONTENT";
    TypeErrorDefault["MULTI_STATUS"] = "MULTI_STATUS";
    TypeErrorDefault["ALREADY_REPORTED"] = "ALREADY_REPORTED";
    TypeErrorDefault["IM_USED"] = "IM_USED";
    TypeErrorDefault["MULTIPLE_CHOICES"] = "MULTIPLE_CHOICES";
    TypeErrorDefault["MOVED_PERMANENTLY"] = "MOVED_PERMANENTLY";
    TypeErrorDefault["FOUND"] = "FOUND";
    TypeErrorDefault["SEE_OTHER"] = "SEE_OTHER";
    TypeErrorDefault["NOT_MODIFIED"] = "NOT_MODIFIED";
    TypeErrorDefault["USE_PROXY"] = "USE_PROXY";
    TypeErrorDefault["TEMPORARY_REDIRECT"] = "TEMPORARY_REDIRECT";
    TypeErrorDefault["PERMANENT_REDIRECT"] = "PERMANENT_REDIRECT";
    TypeErrorDefault["BAD_REQUEST"] = "BAD_REQUEST";
    TypeErrorDefault["UNAUTHORIZED"] = "UNAUTHORIZED";
    TypeErrorDefault["PAYMENT_REQUIRED"] = "PAYMENT_REQUIRED";
    TypeErrorDefault["FORBIDDEN"] = "FORBIDDEN";
    TypeErrorDefault["NOT_FOUND"] = "NOT_FOUND";
    TypeErrorDefault["METHOD_NOT_ALLOWED"] = "METHOD_NOT_ALLOWED";
    TypeErrorDefault["NOT_ACCEPTABLE"] = "NOT_ACCEPTABLE";
    TypeErrorDefault["PROXY_AUTHENTICATION_REQUIRED"] = "PROXY_AUTHENTICATION_REQUIRED";
    TypeErrorDefault["REQUEST_TIMEOUT"] = "REQUEST_TIMEOUT";
    TypeErrorDefault["CONFLICT"] = "CONFLICT";
    TypeErrorDefault["GONE"] = "GONE";
    TypeErrorDefault["LENGTH_REQUIRED"] = "LENGTH_REQUIRED";
    TypeErrorDefault["PRECONDITION_FAILED"] = "PRECONDITION_FAILED";
    TypeErrorDefault["PAYLOAD_TOO_LARGE"] = "PAYLOAD_TOO_LARGE";
    TypeErrorDefault["URI_TOO_LONG"] = "URI_TOO_LONG";
    TypeErrorDefault["UNSUPPORTED_MEDIA_TYPE"] = "UNSUPPORTED_MEDIA_TYPE";
    TypeErrorDefault["RANGE_NOT_SATISFIABLE"] = "RANGE_NOT_SATISFIABLE";
    TypeErrorDefault["EXPECTATION_FAILED"] = "EXPECTATION_FAILED";
    TypeErrorDefault["IM_A_TEAPOT"] = "IM_A_TEAPOT";
    TypeErrorDefault["MISDIRECTED_REQUEST"] = "MISDIRECTED_REQUEST";
    TypeErrorDefault["UNPROCESSABLE_ENTITY"] = "UNPROCESSABLE_ENTITY";
    TypeErrorDefault["LOCKED"] = "LOCKED";
    TypeErrorDefault["FAILED_DEPENDENCY"] = "FAILED_DEPENDENCY";
    TypeErrorDefault["TOO_EARLY"] = "TOO_EARLY";
    TypeErrorDefault["UPGRADE_REQUIRED"] = "UPGRADE_REQUIRED";
    TypeErrorDefault["PRECONDITION_REQUIRED"] = "PRECONDITION_REQUIRED";
    TypeErrorDefault["TOO_MANY_REQUESTS"] = "TOO_MANY_REQUESTS";
    TypeErrorDefault["REQUEST_HEADER_FIELDS_TOO_LARGE"] = "REQUEST_HEADER_FIELDS_TOO_LARGE";
    TypeErrorDefault["UNAVAILABLE_FOR_LEGAL_REASONS"] = "UNAVAILABLE_FOR_LEGAL_REASONS";
    TypeErrorDefault["INTERNAL_SERVER_ERROR"] = "INTERNAL_SERVER_ERROR";
    TypeErrorDefault["NOT_IMPLEMENTED"] = "NOT_IMPLEMENTED";
    TypeErrorDefault["BAD_GATEWAY"] = "BAD_GATEWAY";
    TypeErrorDefault["SERVICE_UNAVAILABLE"] = "SERVICE_UNAVAILABLE";
    TypeErrorDefault["GATEWAY_TIMEOUT"] = "GATEWAY_TIMEOUT";
    TypeErrorDefault["HTTP_VERSION_NOT_SUPPORTED"] = "HTTP_VERSION_NOT_SUPPORTED";
    TypeErrorDefault["VARIANT_ALSO_NEGOTIATES"] = "VARIANT_ALSO_NEGOTIATES";
    TypeErrorDefault["INSUFFICIENT_STORAGE"] = "INSUFFICIENT_STORAGE";
    TypeErrorDefault["LOOP_DETECTED"] = "LOOP_DETECTED";
    TypeErrorDefault["BANDWIDTH_LIMIT_EXCEEDED"] = "BANDWIDTH_LIMIT_EXCEEDED";
    TypeErrorDefault["NOT_EXTENDED"] = "NOT_EXTENDED";
    TypeErrorDefault["NETWORK_AUTHENTICATION_REQUIRED"] = "NETWORK_AUTHENTICATION_REQUIRED";
})(TypeErrorDefault || (TypeErrorDefault = {}));
export const TypeError = {
    ...TypeErrorDefault,
    ...TypeErrorCustom
};
