services:
  postgres:
    image: postgres:16
    pull_policy: never
    container_name: postgres-dev
    env_file:
      - postgres.env
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HTTP_PROXY: ${HTTP_PROXY}
        HTTPS_PROXY: ${HTTPS_PROXY}
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
    container_name: service-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/service/node_modules
      - /app/apps/web/node_modules
      - /app/packages/node_modules
      - /app/.pnpm-store
    depends_on:
      - postgres
    command: pnpm --filter service dev

  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HTTP_PROXY: ${HTTP_PROXY}
        HTTPS_PROXY: ${HTTPS_PROXY}
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
    container_name: web-app
    ports:
      - "5173:5173"
    env_file:
      - apps/web/.env
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/service/node_modules
      - /app/apps/web/node_modules
      - /app/packages/node_modules
      - /app/.pnpm-store
    depends_on:
      - service
    command: pnpm --filter web exec vite --host 0.0.0.0

volumes:
  postgres_data:
