services:
  postgres:
    image: postgres:16
    container_name: postgres-dev
    env_file:
      - postgres.env
    ports:
      - "5434:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data

  service:
    build: .
    container_name: service-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - postgres
    command: pnpm dev

volumes:
  postgres_data:
