import { BirthDate } from "../../valuesObjects/birthDate.js";
import { CPF } from "../../valuesObjects/cpf.js";
import { Email } from "../../valuesObjects/email.js";
import { Name } from "../../valuesObjects/name.js";
import { UserId } from "../../valuesObjects/userId.js";
export declare class UserAuth {
    readonly id: UserId;
    private name;
    private email;
    private passwordHash;
    private isActive;
    private profilePhotoUrl;
    private birthDate;
    private cpf;
    readonly createdAt: Date;
    private updatedAt;
    constructor(id: UserId, name: Name, email: Email, passwordHash: string, isActive: boolean, profilePhotoUrl: string | null, birthDate: BirthDate, cpf: CPF, createdAt: Date, updatedAt: Date);
    changePassword(newHash: string): void;
    getPasswordHash(): string;
    getName(): Name;
    changeProfilePhoto(url: string): void;
    getProfilePhoto(): string | null;
    deactivate(): void;
    isEnabled(): boolean;
    getBirthDate(): BirthDate;
    getCpf(): CPF;
    getEmail(): Email;
    getId(): UserId;
    private touch;
}
